### ISSUE TITLE
feat(command:build): add optional scss\sass\less builds

### ISSUE THREAD

**Issue by valorkin** [valor-software/npm-submodules#2]

**Comment by ocombe** [comment]
Shouldn't it just be one of the step of your `npm run build` ?

**Comment by valorkin** [comment]
it is not only about webpack, ngc for example doesn't support scss loaders :)

**Comment by valorkin** [comment]
so styles in component should be css or loaded separately

**Comment by ocombe** [comment]
yeah, that's why I use a webpack loader to transform sass to css and then include it as a style inside my component

**Comment by valorkin** [comment]
it should be configurable and easily extendable set of command for sure
facing it here: https://github.com/swimlane/swui/pull/2

**Comment by valorkin** [comment]
current issue is extract text webpack plugins, it doesn't work with webpack@2..25+

**Comment by ocombe** [comment]
it does with version 2.0.0-beta.4, that's what I'm using on my project with webpack 2.1.0-beta.26

**Comment by ocombe** [comment]
I was thinking about it, then solution could be: pre-build with webpack so that it uses all of your loaders and stuff, and then generate aot from those pre compiled files.
Is it possible to pre-build with webpack and output TS files (not JS files, since ngc needs TS files for aot) ?

**Comment by maxailloud** [comment]
Something basic provided by ngm-cli could be done and it would be awesome.

**Comment by valorkin** [comment]
done
