### ISSUE TITLE
feat(tsm): add e2e and unit tests

### ISSUE THREAD

**Issue by valorkin** [valor-software/npm-submodules#5]

**Comment by maxailloud** [comment]
Do you have any news about this?
I am actually trying to add some tests in my package and it can be useful to have `ngm-cli` launching them.

**Comment by valorkin** [comment]
We end up thinking that it will be out of ngm scope,
Ngm should build... and that's it ;)

**Comment by maxailloud** [comment]
Ok I see, makes sense.
Do you have any clue on how to add testing in a Angular module developed with ngm-cli? (maybe you, or someone else, already did it)

**Comment by valorkin** [comment]
We are using karma, or with angular cli.
You can check in ngx-bootstrap
BTW huge PR will land here soon
